name: tests

on:
- push
- pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Run linters
    #   uses: golangci/golangci-lint-action@v2
    #   with:
    #     version: v1.29

    - name: Run tests
      run: |
        go test -v -covermode=count -coverprofile=coverage.out

    - name: Test the example
      run: |
        cd example
        go run main.go

    - name: Test the cli
      run: |
        cd ~
        go get github.com/jpedro/canned/cli/canned
        export CANNED_PASSWORD="test"
        export CANNED_FILE="test.can"
        canned init
        canned set hello world
        canned ls
        canned env

    - name: Notify slack
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
